<a href="https://colab.research.google.com/github/gukouk176-debug/colab2/blob/main/DataScience_03_ipynb_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第3回　機械学習のためのPython入門
+ 基本的なライブラリーの利用

## NumPy入門
+ 表形式のデータ間の計算を簡単にできるツール群

In [2]:
#配列,ライブラリnumpy使用
#使用するライブラリの宣言import ※asはライブラリを使いやすいように名前の置き換え
import numpy as np

#配列の宣言．　ndarrayを作成
array1 = np.array([1,1,1])
array2 = np.array([3,3,5])

print('array1 =', array1)
print('array2 =', array2)

array1 = [1 1 1]
array2 = [3 3 5]


+ 配列の次元

In [3]:
# 配列の形状（各次元のサイズ）
print(array1.shape)

(3,)


In [4]:
# 配列の「最初の」次元のサイズ
print(len(array1))

3


+ 配列の演算

In [5]:
#配列の演算と表示
array3 = array1 + array2
array4 = array1*array2    # 要素ごとの乗算（内積ではない）
array5 = array4 - array3

print('array4 =', array4)
print('array5 =', array5)

array4 = [3 3 5]
array5 = [-1 -1 -1]


In [6]:
# 内積
np.dot(array1, array2)

np.int64(11)

In [7]:
# ２次元行列
matrix1 = np.array([[2,1,3],[5,4,8],[3,3,2]])
matrix2 = np.array([[5,5,1],[6,1,2],[9,3,7]])

print('matrix1 =\n', matrix1)
print('matrix2 =\n', matrix2)

matrix1 =
 [[2 1 3]
 [5 4 8]
 [3 3 2]]
matrix2 =
 [[5 5 1]
 [6 1 2]
 [9 3 7]]


In [8]:
# 配列の形状
print(matrix1.shape)

(3, 3)


In [9]:
# 2次元行列の計算と表示
matrix3 = matrix1+matrix2
matrix4 = matrix1*matrix2
print('matrix3 =\n', matrix3)
print('matrix4 =\n', matrix4)

#配列の各行,　列の抜き出し
print('matrix4の1行目', matrix4[0])
print('matrix4の2行目', matrix4[1])
print('matrix4の3行目', matrix4[2])

print('matrix4の1行1列目', matrix4[0][0])
print('matrix4の2行3列目', matrix4[1][2])

matrix3 =
 [[ 7  6  4]
 [11  5 10]
 [12  6  9]]
matrix4 =
 [[10  5  3]
 [30  4 16]
 [27  9 14]]
matrix4の1行目 [10  5  3]
matrix4の2行目 [30  4 16]
matrix4の3行目 [27  9 14]
matrix4の1行1列目 10
matrix4の2行3列目 16


In [10]:
# ２次元行列の内積
print('inner product =\n', np.dot(matrix1, matrix2))

inner product =
 [[ 43  20  25]
 [121  53  69]
 [ 51  24  23]]


In [11]:
# 配列の「最初の」次元のサイズ
matrix5 = np.array([[2,1,3],[5,4,8],[3,3,2],[4,3,2]])
print(len(matrix5))

4


In [12]:
# データ型
array1.dtype

dtype('int64')

In [13]:
# 次元数と要素数
print('array1の次元数：', array1.ndim)
print('array1の要素数：', array1.size)

print('matrix1の次元数：', matrix1.ndim)
print('matrix1の要素数：', matrix1.size)

array1の次元数： 1
array1の要素数： 3
matrix1の次元数： 2
matrix1の要素数： 9


In [14]:
#配列の1次元化
print('matrix1 = \n', matrix1)
one_dim_array = matrix1.reshape(-1,)
print('One dimensional array: ', one_dim_array)

#1次元配列の多次元化,変換できない多次元形状だとエラーが出るので注意
#例）9個の1次元配列を２次元化配列にしようとした場合、２次元化できない要素が出てくるためエラーとなる
two_dim_array = matrix1.reshape(3,3)
print('3 x 3 martirx = \n', two_dim_array)

#単なるリスト作成の場合
List =[1,3,6,7]
print('List =',List)
print(List[0])

matrix1 = 
 [[2 1 3]
 [5 4 8]
 [3 3 2]]
One dimensional array:  [2 1 3 5 4 8 3 3 2]
3 x 3 martirx = 
 [[2 1 3]
 [5 4 8]
 [3 3 2]]
List = [1, 3, 6, 7]
1


### 演習1：配列の練習

In [15]:
#配列の練習
#[5,8,7,3,7]のarray配列f1を作成し、その後g1[3,2,1,9,8]とf1の和をもった配列h1を作成

f1 = [5, 8, 7, 3, 7]
g1 = [3, 2, 1, 9, 8]

h1 = f1 + g1

print("f1 =", f1)
print("g1 =", g1)
print("h1 =", h1)


f1 = [5, 8, 7, 3, 7]
g1 = [3, 2, 1, 9, 8]
h1 = [5, 8, 7, 3, 7, 3, 2, 1, 9, 8]


## Pandas入門
+ Python のデータ分析ライブライの１つ

### Series
+ DataFrame の列を抽出したデータ構造

In [16]:
import pandas as pd

ex_pandas_data = pd.Series([0,2,4])
ex_pandas_data

0    0
1    2
2    4
dtype: int64

In [17]:
# index をアルファベットにする
ex_pandas_index_data = pd.Series([0, 2, 4], index=['A', 'B', 'C'])
print(ex_pandas_index_data)

print()  # 改行

print('データの値：', ex_pandas_index_data.values)
print('インデックスの値：', ex_pandas_index_data.index)

A    0
B    2
C    4
dtype: int64

データの値： [0 2 4]
インデックスの値： Index(['A', 'B', 'C'], dtype='object')


### DataFrame
+ 表形式のデータ構造

In [18]:
# NumPyの2次元配列からDataFrameを作る
import numpy as np
import pandas as pd

array1 = np.array([[1,2], [3,4]])
df1 = pd.DataFrame(array1, columns =['AAA', 'BBB'])
print(df1)

print()
print('列名', df1.columns)
print('行名', df1.index)
print('内容\n', df1.values)

   AAA  BBB
0    1    2
1    3    4

列名 Index(['AAA', 'BBB'], dtype='object')
行名 RangeIndex(start=0, stop=2, step=1)
内容
 [[1 2]
 [3 4]]


In [19]:
login_df = pd.DataFrame({'login':['kyutech00', 'kyutech01', 'kyutech02'],
                         'Name':['Alice', 'Bob', 'Carol'],
                         'Campus':['Tobata', 'Iizuka', 'Wakamatsu']})

login_df

login   Name     Campus
0  kyutech00  Alice     Tobata
1  kyutech01    Bob     Iizuka
2  kyutech02  Carol  Wakamatsu

In [20]:
login_df1 = pd.DataFrame({'login':['kyutech03'],
                         'Name':['Dave'],
                         'Campus':['Iizuka']})

print(login_df1, '\n')

print('2つのデータフレームの結合')
# login_df = login_df.append(login_df1, ignore_index = True)
login_df_new = pd.concat([login_df, login_df1], ignore_index = True)

print(login_df_new)

       login  Name  Campus
0  kyutech03  Dave  Iizuka 

2つのデータフレームの結合
       login   Name     Campus
0  kyutech00  Alice     Tobata
1  kyutech01    Bob     Iizuka
2  kyutech02  Carol  Wakamatsu
3  kyutech03   Dave     Iizuka


In [21]:
# 行と列のスイッチ（転置）
login_df_new.T

0          1          2          3
login   kyutech00  kyutech01  kyutech02  kyutech03
Name        Alice        Bob      Carol       Dave
Campus     Tobata     Iizuka  Wakamatsu     Iizuka

In [22]:
# 特定の列を取り出す
print(login_df_new.Name)

print()

print(login_df_new[['login', 'Name']])

0    Alice
1      Bob
2    Carol
3     Dave
Name: Name, dtype: object

       login   Name
0  kyutech00  Alice
1  kyutech01    Bob
2  kyutech02  Carol
3  kyutech03   Dave


In [23]:
login_df_new.drop(['Campus'], axis=1)

login   Name
0  kyutech00  Alice
1  kyutech01    Bob
2  kyutech02  Carol
3  kyutech03   Dave

In [24]:
login_df2 = pd.DataFrame({'login':['kyutech00', 'kyutech01', 'kyutech02', 'kyutech03', 'kyutech04'],
                         'Major':['Engineering', 'Infomatics', 'Life Science', 'Informatics', 'Engineering']})

pd.merge(login_df_new, login_df2)

login   Name     Campus         Major
0  kyutech00  Alice     Tobata   Engineering
1  kyutech01    Bob     Iizuka    Infomatics
2  kyutech02  Carol  Wakamatsu  Life Science
3  kyutech03   Dave     Iizuka   Informatics

In [25]:
print(login_df_new.head(2))

print()

print(login_df_new[1:3])

       login   Name  Campus
0  kyutech00  Alice  Tobata
1  kyutech01    Bob  Iizuka

       login   Name     Campus
1  kyutech01    Bob     Iizuka
2  kyutech02  Carol  Wakamatsu


### 演習2：DataFrameの練習

In [ ]:
# 行と列からなる DataFrame を一つ作成







## Matplotlib入門

In [ ]:
# Matplotlib のインポート
import matplotlib as mpl
import matplotlib.pyplot as plt

# Seaborn のインポート（より詳しくは次のセクション参照）
import seaborn as sns

np.random.seed(0)         # 乱数シードの固定
x = np.random.randn(30)  # 平均0，標準偏差1の正規分布からの30個の乱数
y = np.random.rand(30)   # 0以上，1未満の小数の30個の乱数

plt.figure(figsize=(15,6))

#plt.plot(x, y, 's')
plt.scatter(x, y, s = 50, c = 'red', alpha = 0.5, linewidths = 1, edgecolors = 'blue', marker = '^')

In [ ]:
plt.figure(figsize=[15,6])

# 2行1列のグラフの1つ目
plt.subplot(2,1,1)
x = np.linspace(-10,10, 200)
plt.plot(x, np.sin(x))

# 2つ目
plt.subplot(2,1,2)
y = np.linspace(-10, 10, 100)
plt.plot(y, 2*np.sin(2*y), c = 'purple')

plt.grid(True)

In [ ]:
np.random.seed(0)

plt.figure(figsize=(15,6))

plt.subplot(2,1,1)
# randで0～1の頻度，ビンの数を50個
plt.hist(np.random.rand(10**5), bins = 50, range = (0,1))

plt.grid(True)

plt.subplot(2,1,2)
# randnで正規分布（平均を50に変更，値を10倍），ビンの数を50個
plt.hist(np.random.randn(10**5)*10 + 50, bins = 50, range = (0,100))

plt.grid(True)

### 演習3：Matplotlibの練習

In [ ]:
# 以下の数値をいろいろと変えて，どこが変わるかを観察してください

np.random.seed(0)

plt.figure(figsize=(15,6))

plt.subplot(2,1,1)
# randで0～1の頻度，ビンの数を50個
plt.hist(np.random.rand(10**5), bins = 50, range = (0,1))

plt.grid(True)

plt.subplot(2,1,2)
# randnで正規分布（平均を50に変更，値を10倍），ビンの数を50個
plt.hist(np.random.randn(10**5)*10 + 50, bins = 50, range = (0,100))

plt.grid(True)

In [ ]:
# カリフォルニアの住宅価格データの読み込み
# 経度，緯度，築年数，部屋数，寝室数，人口，世帯数，所得，住宅価格のデータ
housing_df = pd.read_csv('sample_data/california_housing_train.csv')
housing_df.head(5)

In [ ]:
# 列の抽出
housing_partial_df = housing_df[['median_house_value', 'total_rooms', 'total_bedrooms']]
housing_partial_df.head()

In [ ]:
# 所得に対する住宅価格の散布図
plt.xlabel('Median income')
plt.ylabel('Medain house value')
plt.scatter(housing_df['median_income'], housing_df['median_house_value'])

In [ ]:
# 人口に対する住宅価格の散布図
plt.xlabel('Population')
plt.ylabel('Medain house value')
plt.scatter(housing_df['population'], housing_df['median_house_value'], marker='D')

In [ ]:
# bins の数だけ分割したヒストグラム
plt.hist(housing_df['median_house_value'], bins = 30)

In [ ]:
plt.rcParams['figure.figsize'] = (20,10)
housing_df.hist()

plt.show()

In [ ]:
sns.displot(housing_df['population'])

## Seaborn 入門
「An introduction to seaborn」にあるチュートリアルからいくつかを演習問題としています


In [ ]:
# チップの金額のデータセットについての散布図の例

# Import seaborn
import seaborn as sns

# Apply the default theme
sns.set_theme()

# Load an example dataset
tips = sns.load_dataset("tips")

# Create a visualization
sns.relplot(
    data=tips,
    x="total_bill", y="tip", col="time",
    hue="smoker", style="smoker", size="size",
)

In [ ]:
# 回帰モデルの可視化とグリッドによる表示

sns.lmplot(data=tips, x="total_bill", y="tip", col="time", hue="smoker")

In [ ]:
# ヒストグラムを作成

sns.displot(data=tips, x="total_bill", col="time", kde=True)

In [ ]:
# カテゴリーデータ（smoker/non-smoker）の表示

sns.catplot(data=tips, kind="swarm", x="day", y="total_bill", hue="smoker")

### 演習４．種々の値を変更して表示がどのように変わるかを観察してください